FROM apachephp
    RUN apt-get update && apt-get install -y phpmyadmin
    # Install expect
    RUN apt-get install -y expect

    # Install phpMyAdmin
    RUN echo '#!/usr/bin/expect -f' > install-phpmyadmin.sh; \
        echo "set timeout -1" >> install-phpmyadmin.sh; \
        echo "spawn apt-get install -y phpmyadmin" >> install-phpmyadmin.sh; \
        echo "expect \"Configure database for phpmyadmin with dbconfig-common?\"" >> install-phpmyadmin.sh; \
        echo "send \"y\r\"" >> install-phpmyadmin.sh; \
        echo "expect \"Password of the database's administrative user:\"" >> install-phpmyadmin.sh; \
        echo "send \"\r\"" >> install-phpmyadmin.sh; \
        echo "expect \"MySQL application password for phpmyadmin:\"" >> install-phpmyadmin.sh; \
        echo "send \"\r\"" >> install-phpmyadmin.sh; \
        echo "expect \"Web server to reconfigure automatically:\"" >> install-phpmyadmin.sh; \
        echo "send \"1\r\"" >> install-phpmyadmin.sh
    RUN chmod +x install-phpmyadmin.sh
    RUN rm install-phpmyadmin.sh
    CMD apachectl -DFOREGROUND
