version: "3.8"
services:
  base:
    container_name: servidorbase
    image: ubuntuBase
    build: 
      context: ./servidores
      dockerfile: ./Dockerfile
    environment: 
      - USUARIO=morgado
      - PASSWD=1234
    networks: 
      netansible:
          ipv4_address: 172.120.10.2
 
 