version: '3.8'
services:
  sbd:
    container_name: servBD
    hostname: SBD
    domainname: asir.es
    build: 
      context: ./mysql
      dockerfile: ./Dockerfile
    ports:
      - "3306:3306"
    environment: 
      - USUARIO=luis
      - PASSWD=1234
      - HOSTNAME=SBD.asir.es
      - PROYECTO=Jardineria
    #volumes: 
    #  - ./sbd:/var/lib/mysql
    networks: 
      netasir:
          ipv4_address: 172.124.10.3
  sweb:
    container_name: sweb
    hostname: SWEB
    domainname: asir.es
    build: 
      context: ./phpmyAdmin
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment: 
      - USUARIO=luis
      - PASSWD=1234
      - HOSTNAME=SWEB.asir.es
      - PROYECTO=jardineria
      - DOMINIO=jamorgado.es
    volumes:
      - ./phpmyAdmin/sweb:/var/www/html
    networks: 
      netasir:
          ipv4_address: 172.124.10.4 
networks: 
  netasir:
      ipam: 
          driver: default
          config: 
              - subnet: 172.124.10.0/24

