version: "3" 
services:
  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./h_config:/config
    ports:
      - 8500:80
      - 6443:443
    restart: unless-stopped