FROM ubuntu
RUN apt update && apt install -yq --no-install-recommends \
    apt-utils \
    wget \
    nano \
    net-tools \
    curl \
    unzip \
    dos2unix \
    software-properties-common
#indicamos el timezone
ARG TZ=Europe/Madrid
ENV TZ=${TZ}
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
#instalamos php
#RUN add-apt-repository ppa:ondrej/php 
RUN apt-get update && apt-get install -y php \
    php-cli \
    php-fpm \
    php-json \
    php-common \
    php-mysql \
    php-zip \
    php-gd \
    php-mbstring \
    php-curl \
    php-xml \
    php-pear \ 
    php-bcmath \
    unzip \
    curl \
    apache2 
