FROM apachephp
RUN apt-get update
# Install expect
RUN apt-get install -y expect

# Install phpMyAdmin
WORKDIR /root

COPY phpmyadmin.sh /root
RUN chmod +x /root/phpmyadmin.sh
RUN /root/phpmyadmin.sh

sed -i "s/$dbuser=\'usuario\'/$dbuser=\'root\'/g" /etc/phpmyadmin/config-db.php
sed -i "s/$dbserver=\'localhost\'/$dbserver=\'185.166.212.181'\/g" /etc/phpmyadmin/config-db.php

CMD apachectl -DFOREGROUND



