version: '3.7'
services:
  mongodb_contenedor:
    container_name: mongoLibreria
    image: mongo
    env_file: environment.yml
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - ${DATABASE_PORT}:27017