version: '3.8'
services:
  s1:
    container_name: servidor1
    build: 
      context: ./servidores
      dockerfile: ./Dockerfile
    environment: 
      - USUARIO=luis
      - PASSWD=1234
    networks: 
      netansible:
          ipv4_address: 172.130.10.2
  s2:
    container_name: servidor2
    build: 
      context: ./servidores
      dockerfile: ./Dockerfile
    environment: 
      - USUARIO=luis
      - PASSWD=1234
    networks: 
      netansible:
          ipv4_address: 172.130.10.3
  s3:
    container_name: servidor3
    build: 
      context: ./servidores
      dockerfile: ./Dockerfile
    environment: 
      - USUARIO=luis
      - PASSWD=1234
    networks: 
      netansible:
          ipv4_address: 172.130.10.4
  s4:
    container_name: servidor4
    build: 
      context: ./servidores
      dockerfile: ./Dockerfile
    environment: 
      - USUARIO=luis
      - PASSWD=1234
    networks: 
      netansible:
          ipv4_address: 172.130.10.5
networks: 
  netansible:
      ipam: 
          driver: default
          config: 
              - subnet: 172.130.10.0/24

