version: '3.2'

services:

  portainer:
    image: portainer/portainer-ce
    restart: always
    ports:
      - "9000:9000"
      - "8000:8000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - portainer_data:/data
    networks:
      - agent_network

networks:
  agent_network:
    driver: overlay
    attachable: true
volumes:
  portainer_data:
