FROM mysql:v1

#install expect
RUN apt-get install -y expect

WORKDIR /root
ENV MYSQL_ROOT_PASSWORD=usuario
COPY mysqlconf.sh /root
COPY runmysql.sh /root

RUN chmod +x /root/runmysql.sh
RUN ./runmysql.sh


EXPOSE 3306
RUN service mysql start