version: "3"
services:
  db:
    image: "postgres"
    container_name: "dbpostgress"
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_DB=prisma
    ports:
      - "5432:5432"
    volumes:
      - ./src/core/prisma/tmp/postgres:/var/lib/postgresql/data