version: "3.8"
services:
  base:
    container_name: servidorweb
    image: ub-base-apache
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment: 

      - PUERTO=81
    networks: 
      netapache:
          ipv4_address: 172.130.10.2
networks: 
  netapache:
      ipam: 
          driver: default
          config: 
              - subnet: 172.130.10.0/24 
 